### ISSUE TITLE
LIEF will disable #define enums. Please use LIEF_PE_XXXX or LIEF::PE::XXXX instead!

### ISSUE THREAD

**Issue by SuFu123** [hack0z/luject#10]
![image](https://user-images.githubusercontent.com/77719946/218060678-7a1fac79-4af4-463a-8ce1-a54f17e0b774.png)
i was typeing xmake to build on my commander ,but it throws the errors above, i wonder what's wrong with this main.cpp

**Comment by ghotm** [comment]
我是这么解决的
修改`src/lni/main.cpp`中的`lua_objlen`为`lua_rawlen`
然后`xrepo install "libxmake"`
我安装的版本为:
  -> libxmake v2.7.1 [vs_runtime:"MT"]
最后`xmake"`

**Comment by waruqi** [comment]
try it again.

```console
xrepo update-repo
xrepo remove --all -y libxmake
xmake f -c
xmake
```
