### ISSUE TITLE
master branch xmake 

### ISSUE THREAD

**Issue by AI2Hub** [hack0z/luject#9]
### Describe the problem details
Please describe your problem details here.
Clone master branch ，xmake  show this issue

[  5%]: cache compiling.release src/sv/sv/src/semvers.c
[  5%]: cache compiling.release src/sv/sv/src/comp.c
[  6%]: cache compiling.release src/luajit/luajit/src/lj_debug.c
[  6%]: cache compiling.release src/luajit/luajit/src/lib_io.c
[  6%]: cache compiling.release src/luajit/luajit/src/lj_vmmath.c
[  6%]: cache compiling.release src/luajit/luajit/src/lj_mcode.c
[  6%]: cache compiling.release src/luajit/luajit/src/lj_opt_split.c
[  6%]: cache compiling.release src/luajit/luajit/src/lib_debug.c
if you want to get more verbose errors, please see:
  -> /Users/xxxxxx/.xmake/cache/packages/2209/l/libxmake/v2.5.9/installdir.failed/logs/install.txt
error: install failed!

detail logs :

[ 59%]: cache compiling.release src/tbox/tbox/src/tbox/platform/ifaddrs.c
[ 59%]: cache compiling.release src/tbox/tbox/src/tbox/platform/socket.c
[ 59%]: cache compiling.release src/tbox/tbox/src/tbox/platform/poller.c
[ 60%]: cache compiling.release src/tbox/tbox/src/tbox/platform/page.c
[ 60%]: cache compiling.release src/tbox/tbox/src/tbox/platform/addrinfo.c
[ 60%]: cache compiling.release src/tbox/tbox/src/tbox/platform/time.c
[ 60%]: cache compiling.release src/tbox/tbox/src/tbox/platform/semaphore.c
[ 60%]: cache compiling.release src/tbox/tbox/src/tbox/platform/event.c
[ 61%]: cache compiling.release src/tbox/tbox/src/tbox/platform/backtrace.c
[ 61%]: cache compiling.release src/tbox/tbox/src/tbox/platform/path.c
error: src/tbox/tbox/src/tbox/platform/ifaddrs.c:187:17: error: variable 'ipflags' set but not used [-Werror,-Wunused-but-set-variable]
    tb_uint32_t ipflags = 0;

**Comment by waruqi** [comment]
try

```
xrepo update-repo
xmake f -c
xmake
```
